### ISSUE TITLE
compilation aborted for tblite/param/halogen.f90

### ISSUE THREAD

**Issue by tobigithub** [qcxms/QCxMS#13]
Hi,
I tried to compile the current qcxms version 5.1.1 on a clean system. After the first compilation fail I went into each sub directory for the subprojects and executed (I wonder if this is needed):

````
meson setup _build
meson compile -C _build
````

Then back to the main qcxms and 

````
setup build -Dfortran_link_args=-static --reconfigure
ninja -C build
````

however then it stopped with the following error.

````
~/qcxms-build/QCxMS-main$ ninja -C build
ninja: Entering directory `build'
[212/412] Compiling Fortran object subprojects/tblite/libtblite.a.p/src_tblite_param_halogen.f90.o
FAILED: subprojects/tblite/libtblite.a.p/src_tblite_param_halogen.f90.o
ifort -Isubprojects/tblite/libtblite.a.p -Isubprojects/tblite -I../subprojects/tblite -Isubprojects/mctc-lib/libmctc-lib.a.p -Isubprojects/multicharge/libmulticharge.a.p -Isubprojects/dftd4/libdftd4.a.p -I../subprojects/dftd4/include -Isubprojects/s-dftd3/libs-dftd3.a.p -I../subprojects/s-dftd3/include -Isubprojects/toml-f/libtoml-f.a.p -D_FILE_OFFSET_BITS=64 -warn general -warn truncated_source -g -traceback -O2 -g -traceback -fPIC -qopenmp -qopenmp -module subprojects/tblite/libtblite.a.p -gen-dep=subprojects/tblite/libtblite.a.p/src_tblite_param_halogen.f90.o -gen-depformat=make -o subprojects/tblite/libtblite.a.p/src_tblite_param_halogen.f90.o -c ../subprojects/tblite/src/tblite/param/halogen.f90
../subprojects/tblite/src/tblite/param/halogen.f90(21): error #5136: Illegal syntax for IMPLICIT NONE statement.
   implicit none(type, external)
----------------^
compilation aborted for ../subprojects/tblite/src/tblite/param/halogen.f90 (code 1)
[225/412] Compiling Fortran object subprojects/tblite/libtblite.a.p/src_tblite_disp_d4.f90.o
ninja: build stopped: subcommand failed.
````
This might be related to an older Intel compiler XE2019 version I use, see:
https://community.intel.com/t5/Intel-Fortran-Compiler/implicit-none-type-external-discussion/m-p/1192942 and
https://fortran-lang.discourse.group/t/what-does-implicit-none-type-external-do/497/2

code in /subprojects/tblite/src/tblite/param/halogen.f90:
````
module tblite_param_halogen
   use mctc_env, only : wp, error_type, fatal_error
   use tblite_param_serde, only : serde_record
   use tblite_toml, only : toml_table, get_value, set_value, add_table
   implicit none(type, external)
   private

   public :: halogen_record, halogen_mask, count

   character(len=*), parameter :: k_classical = "classical", k_damping = "damping", &
      & k_rscale = "rscale"

   type, extends(serde_record) :: halogen_record
      real(wp) :: damping
      real(wp) :: rscale
   contains

````

There is also another version in /subprojects/tblite/src/tblite/classical/halogen.f90
````
module tblite_classical_halogen
   use mctc_env, only : wp
   use mctc_io, only : structure_type
   use tblite_repulsion_type, only : repulsion_type
   use tblite_data_atomicrad, only : get_atomic_rad
   implicit none

   public :: halogen_correction, new_halogen_correction

````
Is there a way to use that one?  Supposedly one can circumvent that by adding " /warn:externals ", the question is where? 

When running and recompiling everything again I get another error:
````
/qcxms-build/QCxMS-main/subprojects/tblite$ meson compile -C _build
ninja: Entering directory `_build'
[194/343] Compiling Fortran object libtblite.so.0.1.0.p/src_tblite_api_version.f90.o
FAILED: libtblite.so.0.1.0.p/src_tblite_api_version.f90.o
ifort -Ilibtblite.so.0.1.0.p -I. -I.. -Isubprojects/mctc-lib/libmctc-lib.a.p -Isubprojects/multicharge/libmulticharge.a.p -Isubprojects/dftd4/libdftd4.a.p -I../subprojects/dftd4/include -Isubprojects/s-dftd3/libs-dftd3.a.p -I../subprojects/s-dftd3/include -Isubprojects/toml-f/libtoml-f.a.p -D_FILE_OFFSET_BITS=64 -warn general -warn truncated_source -g -traceback -O2 -g -traceback -fPIC -qopenmp -qopenmp -module libtblite.so.0.1.0.p -gen-dep=libtblite.so.0.1.0.p/src_tblite_api_version.f90.o -gen-depformat=make -o libtblite.so.0.1.0.p/src_tblite_api_version.f90.o -c ../src/tblite/api/version.f90
../src/tblite/api/version.f90(20): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [TBLITE_VERSION]
   use tblite_version, only : get_tblite_version
-------^
../src/tblite/api/version.f90(20): error #6580: Name in only-list does not exist or is not accessible.   [GET_TBLITE_VERSION]
   use tblite_version, only : get_tblite_version
------------------------------^
../src/tblite/api/version.f90(37): error #6406: Conflicting attributes or multiple declaration of name.   [GET_TBLITE_VERSION]
   call get_tblite_version(major, minor, patch)
--------^
compilation aborted for ../src/tblite/api/version.f90 (code 1)
[205/343] Compiling Fortran object libtblite.so.0.1.0.p/src_tblite_xtb_h0.f90.o
ninja: build stopped: subcommand failed.
````
Tobias

**Comment by awvwgk** [comment]
Sorry, my fault. You can try again with a Fortran 2018 compliant compiler like Intel 2021 while I fix this issue upstream.

**Comment by awvwgk** [comment]
> When running and recompiling everything again I get another error

Also, which version of meson / ninja are you using? You can try to upgrade to meson 0.57.2 and ninja 1.10, which come with an improved module dependency tracking mechanism, which is more robust and never misses module dependencies like the old one.

**Comment by tobigithub** [comment]
Thank you.

I installed both versions from git and just use them via export path.
meson -- version 0.59.99
ninja --version: 1.9.0

Also I use the parallel studio XE 2019, but I think its now oneAPI. Can I use that for compiling XTB and QCxMS?
https://software.intel.com/content/www/us/en/develop/articles/free-intel-software-developer-tools.html

````
2021: Intel recently announced the release of a brand new version of Intel Parallel Studio, 
known as the Intel oneAPI, which is now freely available to the entire public community. 
Everyone can now freely use the Intel compilers and HPC libraries.
````
Otherwise I rather wait, because I know the old compilers work.
Thanks

**Comment by awvwgk** [comment]
For decent Fortran support in meson >=0.57.2 the dynamic dependency support in ninja is needed (added in 1.10). Otherwise meson can “miss” a dependency. At the current scale of `xtb` and `QCxMS` this unfortunately has a very high chance of happening.

I'll look into a way to require 0.57.2 and ninja 1.10 for the build to avoid running into this error again.

Intel 19 should be fine once I added the patch, just purge all the directories in `subprojects/*/` first.

**Comment by awvwgk** [comment]
Just fixed the issue in `tblite` upstream, update by `rm -rf subprojects/tblite/` and than rerun meson. There is no need to compile the subprojects separately, meson will automatically take care of it.

**Comment by tobigithub** [comment]
Hi Sebastian,

````
setup build -Dfortran_link_args=-static --reconfigure
ninja -C build
````
and it works like a charm!
Thanks so much.
Tobias
