### ISSUE TITLE
Allow for flexible distances between ion and collision gas in qcxms.in settings file [improvement]

### ISSUE THREAD

**Issue by tobigithub** [qcxms/QCxMS#19]
Hi,
in order to save  simulation time it would be interesting to allow for flexible settings for the collision gas and the ion distance.  In the current code this is hard coded as start_dist = 25 Angstrom in CID.f90

https://github.com/qcxms/QCxMS/search?q=start_dist

````
!Initial hardcoded parameter block
start_dist = 25 * aatoau !distance for Ar-M

`````
Especially for DFT, MP2 and CCSD calculations this could shave off some minutes in calculation times, moreover this could be calculated automatically from the molecular volume of the ion under investigation. In cases where this distance is very near, few trajectories could fail, but overall time savings could be much larger. 

Based on prior experiments a distance of 2-4 VdW radii should be safe, but I did not validate that thoroughly. For example in case of a long cigar shaped molecule, lets say a long chain fatty acid, the collision gas distance could be different, based on the vector, basically shaped similar to the solvent accessible surface plus some safety distance, to not allow any interactions. 

I did not fully test this, especially in a thermostat settings which requires calibration or heating/cooling, but I am just concerned about shortening simulation times here.
Tobias

Tobias

**Comment by JayTheDog** [comment]
Fixed in version 5.1.3.
Set distance by using `dist <no. of steps>` or let the program automatically determine this (see release notes)
