### ISSUE TITLE
DFT calculations under TurboMole do not recognize correct CPU core count or OMP settings

### ISSUE THREAD

**Issue by tobigithub** [qcxms/QCxMS#20]
Hi,
when running QCxMS  Version 5.1.1 the TurboMole subroutine does not recognized the correct
CPU core count. Running "pqcxms 1" will only run on one core, while  "pqcxms 8" will run on multiple trajectories (as intended),
but only on one CPU core each.

Expected behavior would be to use all the current CPU cores for a single trajectory simulation, instead of a single CPU core.

When using GFN2-xtb and the old pqcxms we can run "pqcxms 1" and it will use all the settings deployed in the
OMP_NUM_THREADS environment variable. https://www.openmp.org/spec-html/5.0/openmpse50.html

I am not sure if the molecular dynamics settings in qcxms (outside frog) allow for multiple CPU core use,
but if they do it would be important to enable multiple CPU core calculations for the MD steps. Currently
only a single CPU core is used. 

When using the TurboMole GUI, RIDft.exe and ridft_mpi.exe in older versions, they actually allow for parallel execution of DFT simulations (multiple CPU core usage). 
Tobias

**Comment by feacluster** [comment]
Wondering if anyone has an example to use turbomole SMP ( ridft_OMP ) with multiple cpus. I tried editing the q-batch file with these variables but ridft_OMP seems to max. out at 200% cpu despite the machine having 10 cpus:

```
export OMP_NUM_THREADS=10
export TM_PAR_OMP=on

module purge
module load turbomole/7.5.2/smp
qcxms -P 10 -prod > qcxms.out 2>&1
```
