### ISSUE TITLE
Failed to build with GCC

### ISSUE THREAD

**Issue by ysagon** [qcxms/QCxMS#48]
Dear team,

I'm trying to compile QCxMS using Meson and Ninja and GCC.

It fails with this message: 

```
The Meson build system
Version: 0.58.0
Source dir: /dev/shm/ebbuild/QCxMS/5.1.3/foss-2021a/QCxMS-v.5.1.3
Build dir: /dev/shm/ebbuild/QCxMS/5.1.3/foss-2021a/easybuild_obj
Build type: native build
Project name: qcxms
Project version: 5.1.3
Fortran compiler for the host machine: gfortran (gcc 10.3.0 "GNU Fortran (GCC) 10.3.0")
Fortran linker for the host machine: gfortran ld.gold 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64

../QCxMS-v.5.1.3/config/meson.build:14:2: ERROR: Problem encountered: This project does not support compilation with GCC yet
```

What compiler should I use instead of GCC?

Thanks

**Comment by awvwgk** [comment]
We usually compile with Intel Fortran.

There is also a pending patch to enable compilation with GCC at https://github.com/qcxms/QCxMS/pull/47

**Comment by ysagon** [comment]
Hi,
thanks for the merge. I've tried this new version. I've an issue, BLAS isn't found. I've tried with OpenBLAS in the path. Should I try with another implementation?
