### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by feacluster** [qcxms/QCxMS#54]
Probably doing something wrong, but here's the error when trying to untar the latest release:

```
[~]$  tar -xvzf QCxMS.v.5.1.3.tar.xz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by awvwgk** [comment]
The tarball is compressed with `xz` rather than `gz`, therefore the `gzip` program rightfully complains. Either use `xvJf` to signal `xz` compression or let `tar` choose the decompression algorithm by itself with `xvf`.
