### ISSUE TITLE
Deionization of compound after the ground state trajectory

### ISSUE THREAD

**Issue by 4psireal2** [qcxms/QCxMS#60]
I ran `qcxms` for the first time and by the second run `qcxms`, I got this error 

``` 
reading qcxms.gs ...
--- Checking QC method for ions ---
 
 initializing GFN1-xTB ...
 initialization successful!
 energy =      -66.63494
 charge =              1
 mult   =              1
 etemp  =         5000.0
 initializing S=0 state using HS-UHF.
--- QC method okay ---
 
 *******************************************
       generating randomized ensemble 
 *******************************************
 reading inital coord/velo from qcxms.gs ...
 doing XTB for MO spectrum for M ...
 QM code failure
 prog   =            7
 charge =            0
 mult   =            2
QC initialization error
```

The `coord` and `qcxms.in` input files:
[coord.txt](https://github.com/qcxms/QCxMS/files/11122151/coord.txt)
[qcxms.in.txt](https://github.com/qcxms/QCxMS/files/11122155/qcxms.in.txt)

**Comment by tobigithub** [comment]
QCxMS works with two general mode, for EI-MS (GC-MS) and CID-MS/MS (LC-MS/MS).
Depending on that you need to choose your input molecule and parameter set. 

@psireal9 Your example looks like N-potonated [codeine](https://www.chemspider.com/Chemical-Structure.4447447.html), as [M+H]+ adduct with the molecular formula C18H21NO3+ Meaning you want to calculate the CID-MS/MS? Then you should try with the standard CID-MS/MS settings:
`````
xtb2
cid
elab 60                                                                                                                                
maxcoll 6
noesi
````

In case you want to calculate the 70eV EI-MS (for GC-MS) spectrum, you need to remove the proton and add the neutral molecule as optimized 3D. 
![image](https://user-images.githubusercontent.com/2569565/229327641-0f94f667-62b7-4531-8f94-7840180c61cf.png)
