### ISSUE TITLE
Docker execution for the own compilation fails because it does not find mkl_intel_lp64 library

### ISSUE THREAD

**Issue by pluckySquid** [qcxms/QCxMS#72]
I am trying to compile the project in a docker container, I have installed all the requirements and still it does not find the mkl_intel_lp64 library. It might be a problem of environmental variables but honestly I tried a lot of them and did not get anything. 
Which environment or command line arguments should be established to build QXCMS by our own?

Thanks in advance

#29 3.550 The Meson build system
#29 3.550 Version: 0.61.2
#29 3.550 Source dir: /QCxMS/QCxMS
#29 3.550 Build dir: /QCxMS/QCxMS/build
#29 3.550 Build type: native build
#29 3.550 Project name: qcxms
#29 3.550 Project version: 5.2.0
#29 3.550 Fortran compiler for the host machine: /opt/intel/oneapi/compiler/2023.2.0/linux/bin/intel64/ifort (intel 2021.10.0 "ifort (IFORT) 2021.10.0 20230609")
#29 3.550 Fortran linker for the host machine: /opt/intel/oneapi/compiler/2023.2.0/linux/bin/intel64/ifort ld.bfd 2.38
#29 3.550 Host machine cpu family: x86_64
#29 3.550 Host machine cpu: x86_64
#29 3.550 Run-time dependency OpenMP found: YES 5.0-revision1
#29 3.550 Compiler for language c for the host machine not found.
#29 3.550 
#29 3.550 config/meson.build:57:4: ERROR: Fortran shared or static library 'mkl_intel_lp64' not found
#29 3.550 
#29 3.550 A full log can be found at /QCxMS/QCxMS/build/meson-logs/meson-log.txt

**Comment by JayTheDog** [comment]
I did not compile QCxMS with the newest intel compiler so it could be a version problem. However, the line `config/meson.build:57:4: ERROR: Fortran shared or static library 'mkl_intel_lp64' not found` seems that the library is not correctly installed on your PC, or meson is not able to find it. Please check your installation again, as it also seems that you do not have the c compiler installed as well

**Comment by pluckySquid** [comment]
Yes it looks that new oneapi with icx compiler for both c and c++ is not working to build the project. However, it looks that Intel does not offer the 21.0.3 compiler that you used anymore. 
If I compile the meson project with gcc the meson build works but the ninja work does not because it does not find the qopenmp option, so I think that my issue can be solved installing the icc 21.0.3. Do you know where can I get it?
