### ISSUE TITLE
Input variable validity and combination checking [Improvement]

### ISSUE THREAD

**Issue by tobigithub** [qcxms/QCxMS#9]
Hi,
because there are so many settings a fool-proof mechanism could be included. After a lengthy run I got
a warning that I can not mix certain variables, I think this test should be done when the initial ini file is read.
The reason is, that users will not understand the inner workings and just play around with parameters, like me.
So something that is pretty obvious to the developers is not so easy to understand for practitioners. Hence
variable mixes could be checked (early).

````
xtb2
cid
elab 60
lchamb 0.25
fullauto
maxcoll 1

````
got me after the run: 

````
 Number of fragmentations (CollSec) and Number of collisions (CollNo) cant be set both!
````
Tobias

**Comment by JayTheDog** [comment]
Fixed in release v.5.1.1. All combinations that are not allowed are now **stopped** before runs begin or TMPQCXMS folders are created (otherwise the false inputs would be copied as well)
